### ISSUE TITLE
返回的结果与图片不符

### ISSUE THREAD

**Issue by qiushi9** [Zhui-CN/1688_image_search_crawler#1]

**Comment by qiushi9** [comment]
pailitaoCategoryId 不传就好了

**Comment by Zhui-CN** [comment]
> pailitaoCategoryId 不传就好了
嗯嗯，pailitaoCategoryId有待研究是什么值，之前看是0，现在看是1
至于与图片不符，最好测试一下提交个图片，看web端是否能正常返回类似的同款

**Comment by qiushi9** [comment]
那个是搜图界面，产品分类的ID。之前0就是上衣的ID，1是裙装，之前我传了跟衣服不相干的图片发现返回的都是衣服。
谢谢你靓仔，这个帮了我大忙。

**Comment by Zhui-CN** [comment]
> 那个是搜图界面，产品分类的ID。之前0就是上衣的ID，1是裙装，之前我传了跟衣服不相干的图片发现返回的都是衣服。 谢谢你靓仔，这个帮了我大忙。

**Comment by Zhui-CN** [comment]
> 那个是搜图界面，产品分类的ID。之前0就是上衣的ID，1是裙装，之前我传了跟衣服不相干的图片发现返回的都是衣服。 谢谢你靓仔，这个帮了我大忙。

OK，那注释掉pailitaoCategoryId 用平台默认就好
