### ISSUE TITLE
API设为false时， 无法使用了

### ISSUE THREAD

**Issue by alwaysgot200** [Zhui-CN/1688_image_search_crawler#4]
![2024-02-14_165717](https://github.com/Zhui-CN/1688_image_search_crawler/assets/9555002/476b0393-203a-4580-add2-e785f7f1e75a)

**Comment by Zhui-CN** [comment]
> ![2024-02-14_165717](https://private-user-images.githubusercontent.com/9555002/304677007-476b0393-203a-4580-add2-e785f7f1e75a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTg5MDUsIm5iZiI6MTcwODY1ODYwNSwicGF0aCI6Ii85NTU1MDAyLzMwNDY3NzAwNy00NzZiMDM5My0yMDNhLTQ1ODAtYWRkMi1lNzg1ZjdmMWU3NWEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMDMyMzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFhMTUxNTY4YmNjZDFjNjJiZjlhMWEzMDc5NTkyYmQzZjMwNzM2NGIwMzk1MWRkMjk5OGI3MDcyZjYwYTEwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YaCzygvMEOtipQxFD2H8B23Vya2hf1PM-yTkqzXQfHk)

确实如此，暂未安排维护，抱歉

**Comment by Zhui-CN** [comment]
> ![2024-02-14_165717](https://private-user-images.githubusercontent.com/9555002/304677007-476b0393-203a-4580-add2-e785f7f1e75a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjkzMTAsIm5iZiI6MTcxOTIyOTAxMCwicGF0aCI6Ii85NTU1MDAyLzMwNDY3NzAwNy00NzZiMDM5My0yMDNhLTQ1ODAtYWRkMi1lNzg1ZjdmMWU3NWEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTEzNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ5M2ViYmMxMTFmMTFhNDBjMmQ5Yjg4ZTY4OTY3YmYwYTU4NWEzMzNmYmE3YjVmZmQzZTlhYzhkMWM0NWIzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.h7o0Hn5Xx-zJ8iOvCXadS1AxRHdavBl3jVJnQokTQvs)

已更新
