### ISSUE TITLE
能加个微信不？

### ISSUE THREAD

**Issue by niunan2019** [Zhui-CN/1688_image_search_crawler#5]

**Comment by Zhui-CN** [comment]
> _No description provided._

好的

**Comment by niunan2019** [comment]
可以,13691939797
________________________________
发件人: Zhui-CN ***@***.***>
发送时间: 2024年6月24日 11:38
收件人: Zhui-CN/1688_image_search_crawler ***@***.***>
抄送: yanwenhao ***@***.***>; Author ***@***.***>
主题: Re: [Zhui-CN/1688_image_search_crawler] 能加个微信不？ (Issue #5)


Closed #5<https://github.com/Zhui-CN/1688_image_search_crawler/issues/5> as completed.

―
